# Generated by Django 3.2 on 2023-08-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people_registration', '0002_alter_pessoa_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='id',
            new_name='person_id',
        ),
    ]
